config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  root 'pages#landing'
  get 'pages/about'

  get 'profiles/my_photos'
  get 'profiles/subscribes_list'
  get 'profiles/friends_photos'

  get '/profiles/:id/subscribe' => 'profiles#subscribe', as: 'subscribe_profile' 
  get '/profiles/:id/unsubscribe' => 'profiles#unsubscribe', as: 'unsubscribe_profile' 

  get '/profiles/:id' => 'profiles#show', as: "profile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :description, presence: true
  validates :image, presence: true

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable
  has_many :photos
  has_many :subscriptions 
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    if user_signed_in?
      redirect_to "/photos"
    end
  end
 
  def about
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :owner, only: [:edit, :update, :destroy]

  def index
    @photos = Photo.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 2)
  end


  def show
  end


  def new
    @photo = current_user.photos.build
  end


  def edit
  end


  def create
    @photo = current_user.photos.build(photo_params)
      if @photo.save
        redirect_to @photo, notice: 'Photo was successfully created.'
      else
        render :new
      end 
  end


  def update
      if @photo.update(photo_params)
        redirect_to  @photo, notice: 'Photo was successfully updated.'
      else
        render :edit
      end  
  end


  def destroy
    @photo.destroy
      redirect_to photos_url, notice: 'Photo was successfully destroyed.'
  end

  private

    def owner
      @photo = current_user.photos.find_by(id: params[:id])
      redirect_to photos_path, notice: "У вас нет разрешения на изменение этой фотографии" if @photo.nil?
    end

    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:description, :image)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :set_user, except: [:my_photos, :subscribes_list, :friends_photos]

  def show
  end

   def subscribe
    if current_user.id == @user.id
     redirect_to profile_path(@user), notice: "Вы не можете подписаться на самого себя"
    else
       if current_user.subscriptions.exists?(freind_id: @user.id)
       redirect_to profile_path(@user), notice: "Вы уже подписаны на данного пользователя"
       else
        @subscription = current_user.subscriptions.build
        @subscription.freind_id = @user.id
        @subscription.save
        if @subscription.save
        redirect_to profile_path(@user), notice: "Вы подписаны на данного пользователя"
        end
       end
    end
  end

  def unsubscribe
     if current_user.id == @user.id
       redirect_to profile_path(@user), notice: "Вы не можете подписаться на самого себя"
     else
       if current_user.subscriptions.exists?(freind_id: @user.id)
        @subscription = current_user.subscriptions.find_by_freind_id(@user.id)
        @subscription.destroy
        redirect_to profile_path(@user), notice: "Вы больше не подписаны на данного пользователя"
       else
         redirect_to profile_path(@user), notice: "Вы не были подписаны на данного пользователя"
      end
    end
  end

  def my_photos
    @photos = current_user.photos.order('created_at DESC')
  end

  def subscribes_list
     @friends = User.where(id: current_user.subscriptions.pluck(:freind_id))
  end

  def friends_photos
     @photos = Photo.where(user_id: current_user.subscriptions.pluck(:freind_id)).order('created_at DESC')
  end

private

   def set_user
    @user = User.find(params[:id])
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pagination_helper.rb
require "will_paginate/view_helpers/action_view"

module PaginationHelper

  module BootstrapRenderer

    def to_html
      html = pagination.map do |item|
        item.is_a?(Fixnum) ?
          page_number(item) :
          send(item)
      end.join(@options[:link_separator])

      html = html_container(html) if @options[:container]

      tag("nav", tag("ul", html, class: @options[:class]))
    end

    protected

    def page_item(text, url, link_status = nil)
      text = text.to_s + tag(:span, "(current)", class: "sr-only") if link_status == "active"
      link_tag = link_status.nil? ? link(text, url, class: "page-link", rel: text) : tag(:span, text, class: "page-link")

      tag(:li, link_tag, class: "page-item #{link_status}")
    end

    def page_number(page)
      link_status = "active" if page == current_page
      page_item(page, page, link_status)
    end

    def gap
      text = @template.will_paginate_translate(:page_gap) { '&hellip;' }
      page_item(text, nil, "disabled")
    end

    def previous_page
      num = @collection.current_page > 1 && @collection.current_page - 1
      previous_or_next_page(num, "← сюда", "← сюда")
    end

    def next_page
      num = @collection.current_page < total_pages && @collection.current_page + 1
      previous_or_next_page(num,"туда →", "Next →")
    end

    def previous_or_next_page(page, text, aria_label)
      link_status = "disabled" unless page
      page_item(text, page, link_status)
    end
  end
end

WillPaginate::ActionView::LinkRenderer.send :include, PaginationHelper::BootstrapRenderer

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_navigation.html.erb
 <% if user_signed_in? %>

<nav class="navbar navbar-light bgnav">
<button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
&#9776;
</button>
    <div class="container">
     <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
        <%= link_to "Instaphoto", root_path, class:'navbar-brand text-logo' %>
        <ul class="nav navbar-nav pullright">


             
               <li class="nav-item  <%= "active" if controller.action_name == 'my_photos' %>" >
                 <%= link_to "Мои фото", profiles_my_photos_path, class:'nav-link' %>
              </li>
             

            <% if controller.action_name == 'subscribes_list' %>

              <li class="nav-item active">
                 <%= link_to "Мои подписки", profiles_subscribes_list_path, class:'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                 <%= link_to "Мои подписки", profiles_subscribes_list_path, class:'nav-link' %>
              </li>
            <% end %>


            
              <li class="nav-item <%= "active" if controller.action_name == 'friends_photos' %>">
                 <%= link_to "Фото друзей", profiles_friends_photos_path, class:'nav-link' %>
              </li>
               
             

             <li class="nav-item">
                <%= link_to current_user.name, edit_user_registration_path, class:'btn btn-primary' %>
            </li>
            
            

           <li class="nav-item">
                <%= link_to "Выйти", destroy_user_session_path, method: :delete, class:'nav-link' %>
           </li>
            
        </ul>
      </div>
    </div>
</nav>

<% else %>

<nav class="navbar navbar-light bg-transparent">
<button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
&#9776;
</button>
    <div class="container">
      <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
          <%= link_to "Instaphoto", root_path, class: 'navbar-brand text-logo landing-logo' %>
          <ul class="nav navbar-nav pullright">


            <% if controller.action_name == "about" %>
           <li class="nav-item active">
             
              <%= link_to "О проекте", pages_about_path, class: 'nav-link ' %>
               </li>
              <% else %>
              <li class="nav-item">
              <%= link_to "О проекте", pages_about_path, class: 'nav-link' %>

           </li>
             <% end %>


             <%if controller_name == "photos" %>
                           <li class="nav-item active">
                        <%= link_to "Фотографии", photos_path, class: 'nav-link ' %>
                        </li>

              <% else %>
                  <li class="nav-item">
                        <%= link_to "Фотографии", photos_path, class: 'nav-link' %>
                    </li>
             <% end %>

            <li class="nav-item">
            <%= link_to "Войти", new_user_session_path, class: 'nav-link' %>
            </li>
          </ul>
      </div>
    </div>
</nav>

<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaphoto</title>
    <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <% if user_signed_in? %>
    <div class="container-fluid   container-login">
  <% else %>
    <div class="container-fluid container-background container-login">
  <% end %>
  <%= render "layouts/navigation" %>
  <div class="container">




       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


    <%= yield %>
    </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <h1 class="display-3">О проекте </h1>
  <p class="lead">InstaPhoto - это социальная сеть для обмена фотографиями </p>


  </p>
</div>

app/views/pages/landing.html.erb
    <% if user_signed_in? %>
   
   <% else %>
   <div class="jumbotron jumbotron-landing">
  <h1 class="display-3">Делитесь своими эмоциями!</h1>
  <p class="lead">Размещайте свои фотографии и подписывайтесь на публикации ваших друзей</p>
  <hr class="my-2">
  <p class="lead">
   
   <%= link_to "Создать аккаунт", new_user_registration_path, class: "btn btn-warning" %>
   
   
   <%= link_to "Войти", new_user_session_path, class: "btn btn-primary" %>
   
  </p>

<% end %>
</div>

app/views/photos/_form.html.erb
<%= form_for(photo, html: { multipart: true }) do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class:"form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description, class:"form-control" %>
  </div>

  <div class="actions">
  <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="card photo-form">

<div class="card-header">
<h2>Редактировать фото</h2>
</div>

<div class="card-block">
<%= render 'form', photo: @photo %>
<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>
</div>

</div> 

app/views/photos/index.html.erb
 <p><%= will_paginate @photos %> </p>
 <% @photos.each do |photo| %>
<div class="card photo-form">

  <div class="card-block">

  <%= link_to photo, class: "photo-link" do %>
     <%= image_tag photo.image.url(:medium) %>
  <% end %>
  <br>
  
  <strong><%= photo.description %></strong><br>
  <%= link_to photo.user.name, profile_path(photo.user_id) %> <br>
  <% if photo.user == current_user %>
   <%= link_to 'Edit', edit_photo_path(photo) %> |
  <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  </div>
</div>
<% end %>
<br>
 <p><%= will_paginate @photos %> </p>
 

app/views/photos/new.html.erb
<div class="card photo-form">

<div class="card-header">
<h2>Создать фото</h2>
</div>

<div class="card-block">
<%= render 'form', photo: @photo %>
<%= link_to 'Back', photos_path %>
</div>

</div> 

app/views/photos/show.html.erb
<div class="card photo-form">
  <div class="card-block">

  <p>
  <%= image_tag @photo.image.url(:large) %><br>
  <strong> <%= @photo.description %></strong><br>
  <%= @photo.user.name if @photo.user %>
  </p>

  <% if @photo.user == current_user %><%= link_to 'Edit', edit_photo_path(@photo) %> |
  <%= link_to 'Destroy', @photo, method: :delete, data: { confirm: 'Are you sure?' } %> | <% end %>
  <%= link_to 'Back', photos_path %>

  </div>
</div> 

app/views/profiles/friends_photos.html.erb
 <% @photos.each do |photo| %>
    <div class="card photo-form">
        <div class="card-block">
        <%= link_to photo, class: "photo-link" do %>
            <%= image_tag photo.image.url(:medium) %>
            <% end %>
            <br>
            <strong><%= photo.description %></strong><br>
            <%= link_to photo.user.name, profile_path(photo.user_id)  %><br>
            
        </div>
    </div>
<% end %>

app/views/profiles/my_photos.html.erb
 <% @photos.each do |photo| %>
    <div class="card photo-form">
        <div class="card-block">
             <%= link_to photo, class: "photo-link" do %>

            <%= image_tag photo.image.url(:medium) %>
            <% end %><br>
            <strong><%= photo.description %></strong><br>
             
            <% if photo.user == current_user %>
                 <%= link_to 'Edit', edit_photo_path(photo) %> |
                <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/profiles/show.html.erb
<%= @user.name %>

<% if current_user.id == @user.id %>
<% else %>
<% if current_user.subscriptions.exists?(freind_id: @user.id) %>
  <%= link_to "Отписаться", unsubscribe_profile_path(@user) %>
<% else %>
  <%= link_to "Подписаться", subscribe_profile_path(@user) %>
<% end %>
<% end %>
<br>

<% @user.photos.each do |photo| %>
    <div class="card photo-form">
        <div class="card-block">
            <%= link_to 'Show', photo %>

            <%= image_tag photo.image.url(:medium) %>
            <% end %>
            <br>
            <strong><%= photo.description %></strong><br>
            <% if photo.user == current_user %>
            | <%= link_to 'Edit', edit_photo_path(photo) %> |
            <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/profiles/subscribes_list.html.erb
 <h2>Мои подписки</h2>
 <% @friends.each do |friend| %>
    <div class="card photo-form">
        <div class="card-block">
            <%= link_to friend.name, profile_path(friend.id) %> |
            <%= link_to "Отписаться", unsubscribe_profile_path(friend.id) %>
        </div>
    </div><br>
<% end %>